spring:
  datasource:
    hikari:
      driver-class-name: org.h2.driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.msa: DEBUG

gateway:
  ip: 127.0.0.1